PORTNAME=       librouteros
PORTVERSION=    3.2.1
CATEGORIES=     sysutils python
MASTER_SITES=   PYPI
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	developer.kg@gmail.com
COMMENT=        Python implementation of MikroTik RouterOS API
WWW=            https://github.com/luqasz/librouteros

LICENSE=        LGPL20
LICENSE_FILE=   ${WRKSRC}/LICENSE

USES=           python:3.6+
USE_PYTHON=     distutils autoplist

NO_ARCH=        yes

.include <bsd.port.mk>
